### creacion del hpa(horizontal pods autoscaling)
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sales-hpa
  namespace: rtc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sales-deployment
  minReplicas: 5
  maxReplicas: 30
  targetCPUUtilizationPercentage: 100
