### creacion del hpa(horizontal pods autoscaling)
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: #{service}#-hpa
  namespace: #{namespace}#
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: #{service}#-deployment
  minReplicas: #{replicas}# 
  maxReplicas: #{max-replicas}# 
  targetCPUUtilizationPercentage: #{target-CPU}#